// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppChart: typeof import('./src/components/AppChart.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    AppTimer: typeof import('./src/components/AppTimer.vue')['default']
    CurrentTime: typeof import('./src/components/CurrentTime.vue')['default']
    GroupedVotingResultChart: typeof import('./src/components/GroupedVotingResultChart.vue')['default']
    ParticlesBackground: typeof import('./src/components/ParticlesBackground.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VotesCountChart: typeof import('./src/components/VotesCountChart.vue')['default']
    VotingSubjectItem: typeof import('./src/components/VotingSubjectItem.vue')['default']
    VotingSubjectsAccordion: typeof import('./src/components/VotingSubjectsAccordion.vue')['default']
    VotingSubjectsAccordionItem: typeof import('./src/components/VotingSubjectsAccordionItem.vue')['default']
    VotingSubjectsList: typeof import('./src/components/VotingSubjectsList.vue')['default']
  }
}

export {}
